spring:
  application:
    #设置当前项目名称，提交到nacos，注册为当前微服务名称
    name: nacos-business
  cloud:
    sentinel:
      transport:
        # 配置sentinel提供的仪表台服务器的位置
        dashboard: localhost:8080
        # 执行限流的端口号,每个项目必须设置不同的端口号,例如cart模块要限流就可以设置为8722
        port: 8722
    nacos:
      discovery:
        #配置nacos的位置，用于提交当前项目信息
        server-addr: localhost:8848
        #设置项目在nacos中存在的时间 true临时  false永久
        #ephemeral: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
seata:
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      csmall_group: default
    grouplist:
      default: localhost:8091
