spring:
  application:
    #设置当前项目名称，提交到nacos，注册为当前微服务名称
    name: nacos-business
  cloud:
    nacos:
      discovery:
        #配置nacos的位置，用于提交当前项目信息
        server-addr: localhost:8848
        #设置项目在nacos中存在的时间 true临时  false永久
        #ephemeral: true

